### ISSUE TITLE
Final value in a cell should be printed out

### ISSUE THREAD

**Issue by goatchurchprime** [adafruit/jupyter_micropython_kernel#8]
This is a feature of normal jupyter notebooks, so you don't have to do print(x) on the last line.  Just do x.

This might be very hard to do, due to the implementation, but it's a very handy convention you get used to with normal jupyter notebooks.

**Comment by ladyada** [comment]
@tdicola on tidyday, please check this issue, and implement if possible

**Comment by tdicola** [comment]
I'm going to close this because it's not really a possible without changing MicroPython itself.  The way this kernel works is it enters the raw REPL mode of the MicroPython board so that it can execute and retrieve results without getting stepped on from REPL output (like the >>> prompt, etc.).  This is a nifty feature of MicroPython so that it can work with tooling like this notebook, upload tools like ampy, etc.  It looks like though the raw REPL mode suppresses the default output of a variable \_\_repr\_\_ result (i.e. just typing a variable name at the REPL is actually calling the variable's \_\_repr\_\_ function internally and printing the result as a convenience).  So the fix here would be to change MicroPython's raw REPL mode, but that could have knock on implications for tooling that depends on the current behavior and is outside the scope of this notebook.  Stick with printing any state explicitly.
